'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';

import { runFullAnalysis, type AnalysisResults } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { CheckCircle2, FileText, Briefcase, Key, AlertTriangle, Download, Loader2, Wand2 } from 'lucide-react';
import { ReportSection } from './report-section';

const formSchema = z.object({
  resume: z.string().min(100, { message: 'Resume must be at least 100 characters long.' }),
  jobDescription: z.string().min(100, { message: 'Job description must be at least 100 characters long.' }),
});

type FormValues = z.infer<typeof formSchema>;

function formatReportText(text: string) {
    // A simple formatter to replace markdown-like syntax with HTML
    return text
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        .replace(/^- (.*$)/gm, '<li style="margin-left: 20px; padding-left: 5px;">$1</li>')
        .replace(/\n/g, '<br />');
}


export default function AtsCalculator() {
  const [results, setResults] = useState<AnalysisResults | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      resume: '',
      jobDescription: '',
    },
  });

  const onSubmit = async (data: FormValues) => {
    setIsLoading(true);
    setResults(null);
    try {
      const analysisResults = await runFullAnalysis(data.resume, data.jobDescription);
      setResults(analysisResults);
    } catch (error) {
      toast({
        variant: 'destructive',
        title: 'Analysis Failed',
        description: error instanceof Error ? error.message : 'An unknown error occurred.',
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  const downloadReport = () => {
    if (!results) return;

    const { resume } = form.getValues();
    const keywordMatch = results.extractedKeywords.filter(kw => 
      new RegExp(`\\b${kw}\\b`, 'i').test(resume)
    );

    const reportContent = `
# ATS Compatibility Report

## 1. ATS Compatibility Check
${results.compatibilityReport}

## 2. Keyword Analysis (from Job Description)
- Total Keywords Extracted: ${results.extractedKeywords.length}
- Keywords Found in Resume: ${keywordMatch.length}
- Missing Keywords: ${results.extractedKeywords.filter(kw => !keywordMatch.includes(kw)).join(', ')}

**Extracted Keywords:**
${results.extractedKeywords.map(kw => `- ${kw}`).join('\n')}

## 3. ATS Error Identification
${results.errorAnalysis}

## 4. General Formatting Recommendations
- Use standard, readable fonts like Arial, Calibri, or Georgia.
- Avoid using tables, columns, or text boxes as they can be misread by ATS.
- Use standard section headings like "Work Experience", "Education", and "Skills".
- Ensure your contact information is at the top and clearly labeled.
- Submit your resume as a .docx or .pdf file unless specified otherwise.

---
This report was generated by ATS Calculator.
    `;

    const blob = new Blob([reportContent.trim()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'ATS_Report.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const resumeText = form.watch('resume');
  const matchedKeywords = results ? results.extractedKeywords.filter(kw => new RegExp(`\\b${kw}\\b`, 'i').test(resumeText)) : [];

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:items-start">
      <Card className="w-full">
        <CardHeader>
          <CardTitle className="font-headline text-2xl">Analyze Your Resume</CardTitle>
          <CardDescription>
            Paste your resume and a job description to get an instant ATS compatibility score and analysis.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="resume"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center gap-2 font-semibold">
                      <FileText className="h-4 w-4" /> Resume Content
                    </FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Paste the full text content of your resume here..."
                        className="min-h-[250px] resize-y"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="jobDescription"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center gap-2 font-semibold">
                      <Briefcase className="h-4 w-4" /> Job Description
                    </FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Paste the full job description here..."
                        className="min-h-[250px] resize-y"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <Wand2 className="mr-2 h-4 w-4" />
                    Run ATS Analysis
                  </>
                )}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
      
      <div className="sticky top-24">
        {isLoading && (
          <Card className="flex h-[400px] flex-col items-center justify-center text-center">
            <Loader2 className="h-12 w-12 animate-spin text-primary" />
            <p className="mt-4 font-headline text-xl font-semibold">Analyzing your documents...</p>
            <p className="mt-2 text-muted-foreground">Our AI is working its magic. This may take a moment.</p>
          </Card>
        )}

        {!isLoading && results && (
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="font-headline text-2xl">Analysis Report</CardTitle>
                <CardDescription>Your resume has been analyzed against the job description.</CardDescription>
              </div>
              <Button variant="outline" size="sm" onClick={downloadReport}>
                <Download className="mr-2 h-4 w-4" />
                Download Report
              </Button>
            </CardHeader>
            <CardContent>
              <Tabs defaultValue="compatibility">
                <TabsList className="grid w-full grid-cols-4">
                  <TabsTrigger value="compatibility">Compatibility</TabsTrigger>
                  <TabsTrigger value="keywords">Keywords</TabsTrigger>
                  <TabsTrigger value="errors">Errors</TabsTrigger>
                  <TabsTrigger value="formatting">Formatting</TabsTrigger>
                </TabsList>
                <TabsContent value="compatibility" className="mt-4">
                  <ReportSection icon={CheckCircle2} title="ATS Compatibility Check">
                    <div className="text-sm space-y-2" dangerouslySetInnerHTML={{ __html: formatReportText(results.compatibilityReport) }} />
                  </ReportSection>
                </TabsContent>
                <TabsContent value="keywords" className="mt-4">
                  <ReportSection icon={Key} title="Keyword Analysis">
                    <p className="mb-4 text-sm text-muted-foreground">
                      We found <span className="font-bold text-primary">{matchedKeywords.length}</span> out of <span className="font-bold text-primary">{results.extractedKeywords.length}</span> keywords from the job description in your resume.
                    </p>
                    <div className="space-y-3">
                      <div>
                        <h4 className="font-semibold text-sm mb-2">Keywords Matched:</h4>
                        <div className="flex flex-wrap gap-2">
                          {matchedKeywords.length > 0 ? matchedKeywords.map(kw => <Badge key={kw} variant="secondary" className="border-green-200 bg-green-100 text-green-800 dark:border-green-700 dark:bg-green-900/50 dark:text-green-300">{kw}</Badge>) : <p className="text-sm text-muted-foreground">None</p>}
                        </div>
                      </div>
                      <div>
                        <h4 className="font-semibold text-sm mb-2">Keywords Missing:</h4>
                        <div className="flex flex-wrap gap-2">
                           {results.extractedKeywords.filter(kw => !matchedKeywords.includes(kw)).map(kw => <Badge key={kw} variant="destructive">{kw}</Badge>)}
                        </div>
                      </div>
                    </div>
                  </ReportSection>
                </TabsContent>
                <TabsContent value="errors" className="mt-4">
                  <ReportSection icon={AlertTriangle} title="Potential Error Identification">
                    <div className="text-sm space-y-2" dangerouslySetInnerHTML={{ __html: formatReportText(results.errorAnalysis) }} />
                  </ReportSection>
                </TabsContent>
                <TabsContent value="formatting" className="mt-4">
                  <ReportSection icon={Wand2} title="Formatting Recommendations">
                    <ul className="space-y-2 text-sm text-foreground">
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Use standard, readable fonts like Arial, Calibri, or Georgia.</span></li>
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Avoid using tables, columns, or text boxes, as they can be misread by ATS.</span></li>
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Use standard section headings like "Work Experience", "Education", and "Skills".</span></li>
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Ensure your contact information is at the top and clearly labeled.</span></li>
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Submit your resume as a .docx or .pdf file unless specified otherwise.</span></li>
                      <li className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span>Avoid headers and footers for important information like contact details.</span></li>
                    </ul>
                  </ReportSection>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        )}

        {!isLoading && !results && (
          <Card className="flex h-[400px] flex-col items-center justify-center p-8 text-center">
            <div className="rounded-full bg-primary/10 p-4">
                <Wand2 className="h-10 w-10 text-primary" />
            </div>
            <p className="mt-4 font-headline text-xl font-semibold">Ready to Optimize?</p>
            <p className="mt-2 max-w-xs text-muted-foreground">Fill in the form to the left to see how your resume stacks up against applicant tracking systems.</p>
          </Card>
        )}
      </div>
    </div>
  );
}
